button:
 -
  name: "点餐"
  sub_button:
   -
    type: "view"
    name: "新品推荐"
    url:  "http://zhu.natapp1.cc/wechat/stores"
   -
    type: "view"
    name: "预订午餐"
    url:  "http://zhu.natapp1.cc/wechat/stores"
   -
    type: "view"
    name: "预订晚餐"
    url:  "http://zhu.natapp1.cc/wechat/stores"
 -
  type: "view"
  name: "我的订单"
  url:  "http://zhu.natapp1.cc/wechat/stores"
 -
  type: "view"
  name: "关于"
  url:  "http://zhu.natapp1.cc/users/auth/wechat"
